sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=Solenopsis
    - OS_ARCH=noarch
    - NAME=solenopsis
    - VERSION=1.2
    - RPM_BUILD_ROOT=/tmp/rpm
    - RPM_BUILD_DIR=/tmp/rpm/BUILD
    - RPM_ROOT_DIR=.
    - RPM_SOURCE_DIR=/tmp/rpm/SOURCES
    - NAME=solenopsis
    - VERSION=1.2
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

install: true

before_script:
  - sudo apt-get install -y rpm

script:
  - mkdir -p /tmp/rpm/BUILD /tmp/rpm/RPMS /tmp/rpm/SOURCES /tmp/rpm/SPECS /tmp/rpm/SRPMS
  - mkdir -p /tmp/solenopsis-1.2
  - cp -a * /tmp/solenopsis-1.2/
  - ls -la /tmp/solenopsis-1.2/
  - tar czf /tmp/rpm/SOURCES/solenopsis-1.2.tar.gz -C /tmp/solenopsis-1.2
  - ls -la /tmp/solenopsis-1.2
  - rpmbuild --define "_topdir /tmp/rpm" -ba solenopsis.spec

after_success:
  - eche Done